name: cochrane-mac
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - asn1crypto=0.24.0
  - beautifulsoup4=4.8.0
  - boto=2.49.0
  - boto3=1.9.216
  - botocore=1.12.216
  - bz2file=0.98
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - clangdev=4.0.0
  - cryptography=2.7
  - cycler=0.10.0
  - docutils=0.15.2
  - freetype=2.10.0
  - gensim=3.4.0
  - icu=64.2
  - idna=2.8
  - jmespath=0.9.4
  - joblib=0.13.2
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.4
  - libxgboost=0.90
  - libxml2=2.9.9
  - lightgbm=2.2.3
  - llvm-openmp=4.0.1
  - llvmdev=4.0.0
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - ncurses=6.1
  - nltk=3.4.4
  - numpy=1.16.4
  - openmp=4.0.0
  - openssl=1.1.1c
  - pandas=0.25.1
  - pip=19.2.3
  - psycopg2=2.7.6.1
  - py-xgboost=0.90
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pysocks=1.7.0
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyyaml=5.1.2
  - readline=7.0
  - requests=2.22.0
  - s3transfer=0.2.1
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - setuptools=41.2.0
  - six=1.12.0
  - smart_open=1.8.4
  - soupsieve=1.9.3
  - sqlalchemy=1.3.7
  - sqlite=3.29.0
  - tk=8.6.9
  - tornado=6.0.3
  - tqdm=4.35.0
  - urllib3=1.25.3
  - wheel=0.33.6
  - xgboost=0.90
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
