name: cochrane-linux
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - asn1crypto=0.24.0
  - beautifulsoup4=4.8.0
  - blas=1.0
  - boto=2.49.0
  - boto3=1.9.199
  - botocore=1.12.199
  - bz2file=0.98
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - cycler=0.10.0
  - dbus=1.13.6
  - docutils=0.14
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gensim=3.4.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - jmespath=0.9.4
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libpq=11.2
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxgboost=0.90
  - libxml2=2.9.9
  - lightgbm=2.2.3
  - matplotlib=3.1.0
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ncurses=6.1
  - nltk=3.4.4
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1
  - pandas=0.25.1
  - pcre=8.43
  - pip=19.2.3
  - psycopg2=2.7.6.1
  - py-xgboost=0.90
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pysocks=1.7.0
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyyaml=5.1.2
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - s3transfer=0.2.1
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - setuptools=41.0.1
  - sip=4.19.13
  - six=1.12.0
  - smart_open=1.8.4
  - soupsieve=1.9.2
  - sqlalchemy=1.3.7
  - sqlite=3.29.0
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.35.0
  - urllib3=1.24.2
  - wheel=0.33.4
  - xgboost=0.90
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
