id:
  17
seed:
  2019
k_folds_seed:
  100
features_table:
  papers_features
labels_table:
  papers_rgs_wide
unique_id:
  recordid
data_type:
  flat
target:
  inregister
existing_features:
  - tokens_no_stopwords
  - so
generated_features:
  - vocab
model_type:
  rf_nostop_simple_journals
hyperparameters:
  # Random Forests
  n_estimators: [10, 100]
  max_depth: [10, 50]
  max_features: ['auto']
  min_samples_leaf: [5, 20]
  n_jobs: [8]
  # TF-IDF
  ngram_range: [1]
  token_pattern: [alpha]
  max_vocab_f: [5000, 10000, 25000]

query:
  ~
condition:
  ~
train_neg_n:
  ~
test_perc:
  0.2
